[pytest]
# 测试目录
testpaths = tests

# pytest 执行 pytest 时，哪些文件、类、函数会被当成测试去执行
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 自定义标记
# 在一些测试类/函数上面会有装饰器，比如 @pytest.mark.ui，@pytest.mark.api 等等，这些就是自定义标记
# 若终端：pytest -m ui，则只会执行带有 @pytest.mark.ui 装饰器的测试类/函数
# pytest -m "ui and smoke"  跑同时满足两个标记
# pytest -m "api and not regression"  跑 API 但不跑回归
markers =
    ui: UI 自动化测试
    api: API 接口测试
    smoke: 冒烟测试
    regression: 回归测试

# 命令行默认选项, 如：加了 -s -v 就不用在启动时加上-s -v 选项，直接 pytest 就可以了
# --reruns=2 用例失败后的最大重试次数
# --reruns-delay=3 失败重试间隔时间
# --clean-alluredir 清理上次的allure-results目录数据，避免查看本次的allure报告时，出现上次的测试结果
addopts =
    -s
    -v
    --alluredir=allure-results
    --clean-alluredir
    --reruns=2
    --reruns-delay=3

# 日志配置（pytest 内置 logging）
# log_cli = true 表示启用日志输出到控制台
# log_cli_level = INFO 表示日志输出的最低级别为 INFO，(Debug(不显示) < INFO < WARNING < ERROR < CRITICAL)
# log_cli_format = [%(asctime)s] [%(levelname)s] [%(name)s] %(message)s 表示日志输出的格式
log_cli = true
log_cli_level = INFO
log_cli_format = [%(asctime)s] [%(levelname)s] [%(name)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

# 忽略目录，即黄色的目录
# 告诉 pytest：测试发现/递归搜索目录时，不要进入这些目录
norecursedirs = .venv allure-results allure-report logs screenshots
